<?php
    //******************************* 1. API USAGE **********************************************
    // Change the name of this file from `api.credentials.sample.inc` to `api.credentials.inc`
    //******************************* 2. API Users Structures ***********************************
    // $api["YOURCLIENTNAME"]["ApiStatus"]  = 0; //1 Enabled, 0 Disabled @int
    // $api["YOURCLIENTNAME"]["ApiDomaine"] = ""; // User Domain-name example `Used to check if request coming from the right user`
    // $api["YOURCLIENTNAME"]["ApiAccess"]  = "courses_list"; // User access list `multi type of access in next release`
    // $api["YOURCLIENTNAME"]["ApiUser"]    = ""; // User name of the Client
    // $api["YOURCLIENTNAME"]["ApiSecret"]  = ""; // User secret key of the Client
    //   ------------------------------------------------------------------------------------------
    //   You can add as much you want of user just change the CLIENTNAME EX :
    //   ------------------------------------------------------------------------------------------
    //   $api["YOURCLIENTNAME2"]["ApiStatus"]  = 0; //1 Enabled, 0 Disabled @int
    //   $api["YOURCLIENTNAME2"]["ApiDomaine"] = ""; // User Domain-name example `Used to check if request coming from the right user`
    //   $api["YOURCLIENTNAME2"]["ApiAccess"]  = "courses_list"; // User access list `multi type of access in next release`
    //   $api["YOURCLIENTNAME2"]["ApiUser"]    = ""; // User name of the Client
    //   $api["YOURCLIENTNAME2"]["ApiSecret"]  = ""; // User secret key of the Client
    //**********************************************************************************************

?>